### PR TITLE
mh services - fairly large update to language, word, and text services

### PR DESCRIPTION
**Pull request by mrchrmn**
Added language, texts and words services and appropriate types and conversion functions. 

There is also an updated schema in there that takes text titles into account when looking for known userwords. Is not easy to implement without all tables relating to texts. But it is also not urgent to do it on the staging DB.

### CODE REVIEW

**Comment by mrchrmn** [comment]
Oh, and I also to HOST and PORT into the `.env` and refer to it in the app. **Please update your .env accordingly.**

**Comment by mrchrmn** [comment]
Oh (again), and I renamed my service functions more clearly, which will require the routes to be updated.

**Review by eamon0989 — CHANGES_REQUESTED** [review]
I got a compile error so I can't test it fuly:

[ERROR] 13:24:39 ⨯ Unable to compile TypeScript:
src/routes/texts.ts:14:34 - error TS2339: Property 'getOne' does not exist on type '{ getAll: () => Promise<Text[] | null>; getById: (textId: number) => Promise<Text | null>; addNew: (textData: Text) => Promise<void>; }'.

14   const text = await textService.getOne(id);

I think you've changed the function name in the service without updating it in the route

**Comment by mrchrmn** [comment]
Names in routes updated. 
Introduced new naming scheme for service object and returned db results. 
Please have a look.

**Pull request merged**
